service: pdf

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  serverless-offline:
    port: 3000
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
    packager: "npm"

package:
  exclude:
    - ./**
  include:
    - node_modules/**
    - handler.js

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: "eu-central-1"

functions:
  service:
    handler: index.handler
    events:
      - http:
          path: /pdf
          method: POST
          cors: true
