service: pdf

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-domain-manager

custom:
  serverless-offline:
    port: 3000
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
    packager: "npm"
  customDomain:
    domainName: pdf.luimey.de
    createRoute53Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2

package:
  exclude:
    - ./**
  include:
    - .webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: "eu-central-1"
  environment:
    STAGE: ${self:provider.stage}
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  logs:
    restApi: true

functions:
  post:
    handler: src/handlers.post
    events:
      - http:
          path: /pdf
          method: POST
          cors: true
  get:
    handler: src/handlers.get
    events:
      - http:
          path: /pdf
          method: GET
          cors: true
