service: pdf

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-domain-manager

custom:
  domains:
    prod: pdf.luimey.de
    dev: staging.pdf.luimey.de
  serverless-offline:
    port: 3000
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
    packager: "npm"
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    createRoute53Record: true
    stage: ${self:provider.stage}

package:
  exclude:
    - ./**
  include:
    - .webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: "eu-central-1"
  environment:
    STAGE: ${self:provider.stage}
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  logs:
    restApi: true

functions:
  post:
    handler: src/handlers.post
    events:
      - http:
          path: /pdf
          method: POST
          cors: true
  get:
    handler: src/handlers.get
    events:
      - http:
          path: /pdf
          method: GET
          cors: true
