service: pdf

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  serverless-offline:
    port: 3000
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
    packager: "npm"

package:
  exclude:
    - ./**
  include:
    - node_modules/**
    - handler.js

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: "eu-central-1"
  environment:
    STAGE: ${self:provider.stage}

functions:
  post:
    handler: src/handlers.post
    events:
      - http:
          path: /pdf
          method: POST
          cors: true
  get:
    handler: src/handlers.get
    events:
      - http:
          path: /pdf
          method: GET
          cors: true
