service: pdf

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3000

package:
  exclude:
    - ./**
  include:
    - node_modules/**
    - handler.js

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: 'eu-central-1'
  environment:
      CHROME_PATH: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'

functions:
  service:
    handler: handler.handler
    events:
      - http:
          path: /pdf
          method: POST
          cors: true