name: Run Testclient

on:
  issue_comment:
    types: [created]

jobs:
  client:
    if: github.event.comment.body == '@github-actions client'
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullResponse = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const checkResponse = await github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Run Testclient",
              head_sha: `${pullResponse.data.head.sha}`,
              status: "in_progress"
            });

            core.setOutput('check_id', `${checkResponse.data.id}`);

      - uses: actions/checkout@master

      - name: Install
        run: npm install

      - name: Test client
        run: npm run client
        env:
          LAMBDA_ENDPOINT: " https://dev-pdf.luimey.de"

      - uses: actions/upload-artifact@v2
        with:
          name: pdf-output
          path: test.pdf

      - name: Clean Up
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = `${{ job.status }}`;
            const conclusion = status == 'success' || status == 'cancelled' ? status : 'failure';

            github.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: `${{ steps.setup.outputs.check_id }}`,
              status: "completed",
              conclusion,
              output: {
                title: "Test Client",
                summary: "Successfully ran test-client"
              } 
            });
