name: Deploy Version

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install
        run: npm install --only=prod

      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage prod
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
